version: '3'
services:
    dbm1:
        build:
            context: ./master1
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: test
            MYSQL_ROOT_PASSWORD: q1w2e3r4

    dbm2:
        build:
            context: ./master2
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - 3406:3306
        environment:
            MYSQL_DATABASE: test
            MYSQL_ROOT_PASSWORD: q1w2e3r4
        depends_on:
            - dbm1

    dba:
        image: adminer:latest
        restart: always
        ports:
            - 3006:8080
        depends_on:
            - dbm1
            - dbm2
