version: '3'
services:
    dbm:
        build:
            context: ./master
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: test
            MYSQL_ROOT_PASSWORD: root

    dbs:
        build:
            context: ./slave
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - 3406:3306
        environment:
            MYSQL_DATABASE: test
            MYSQL_ROOT_PASSWORD: root
        depends_on:
            - dbm

    dba:
        image: adminer:latest
        restart: always
        ports:
            - 3006:8080
        depends_on:
            - dbm
            - dbs
